### ISSUE TITLE
ToDo: study spring spring boot

### ISSUE THREAD

**Issue by chalieK** [chalieK/checklounge#3]
## 목적
그룹 스터디 사이드 프로젝트를 위한 배경지식 공부
## 세부 내용
- [ ] spring, spring boot 개념 공부
- [ ] 위 프레임 워크 간의 차이점 공부
- [ ] 위 프레임 워크 들의 장단점 공부
